baseurl = "https://schwenktheworld.netlify.com/"
languageCode = "en-us"
title = "Schwenk The World"
description = "All about schwenking"
theme = "hugo-theme-blueberry-detox"

[taxonomies]
  category = "categories"
  tag = "tags"


[[menu.main]]
    name = "our mission I"
    weight = -120
    identifier = "our-mission"
    url = "/our-mission"
[[menu.main]]
    name = "video I"
    weight = -110
    identifier = "video"
    url = "/tags/video"
[[menu.main]]
    name = "schwenks I"
    weight = -100
    identifier = "schwenks"
    url = "/tags/schwenks"
[[menu.main]]
    name = "schwenking I"
    weight = -100
    identifier = "schwenking"
    url = "/schwenking"
[[menu.main]]
    name = "get a schwenker"
    weight = -90
    identifier = "get-a-schwenker"
    url = "/get-a-schwenker"